name: Test workflow
on: 
  workflow_dispatch
  
jobs:
  publish:
    name: Publish composite to Github packages 
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
    steps:
      
      - name: Check if config plan exists    
        id: plan
        run: |
          echo "$MY_CFG_PLAN"
          if test -f "$MY_CFG_PLAN" 
            then
              echo "CFGFILE=" 
              echo "CFGFILE=" >> GITHUB_OUTPUT
            else
              echo "CFGFILE=$MY_CFG_PLAN 
              echo "CFGFILE=$MY_CFG_PLAN" >> GITHUB_OUTPUT
          fi          
        env:
          MY_CFG_PLAN: "A/B/C/D.xml"  
      - name: Get Information to trigger SIT deployment
        run: |
          echo $MY_CFGPLAN
        env:
          #MY_CFGPLAN: "/${{ steps.composite.outputs.COMPOSITE_PATH }}/SIT_${{ steps.composite.outputs.COMPOSITE_NAME }}_cfgplan.xml" 
          MY_CFGPLAN: "/${{ steps.plan.outputs.CFGFILE }}"  
     
     
