name: Test workflow
on: 
  workflow_dispatch
  
jobs:
  publish:
    name: Publish composite to Github packages 
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
    steps:
      
      - name: Check if config plan exists    
        id: plan
        run: |
          if test -f "$MY_CFG_PLAN" 
            then
              echo "CFGFILE=" 
              echo "CFGFILE=" >> $GITHUB_OUTPUT
            else
              exit 1
              echo "CFGFILE=$MY_CFG_PLAN"
              echo "CFGFILE=$MY_CFG_PLAN" >> $GITHUB_OUTPUT
          fi    
          exit 1
        env:
          MY_CFG_PLAN: "A/B/C/D.xml"  
          
      - name: Get Information to trigger SIT deployment
        run: |
          echo ${{ steps.plan.outputs.CFGFILE }}
      - name: Always
        if: always() 
        run: |
          if test -z "$TEMPDIR" 
            then
              echo "ssj here"
          fi   
        env:
          TEMPDIR: ${{ steps.plan.outputs.CFGFILE }}
          
     
